apiVersion: v1
kind: Service
metadata:
  name: content-platform-backend-service
spec:
  selector:
    app: content-platform-backend
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP