apiVersion: v1
kind: Service
metadata:
  name: content-platform-frontend-service
spec:
  selector:
    app: content-platform-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer